In [1]:
import pandas as pd
import numpy as np

In [13]:
nba=pd.read_csv("nba.csv")
nba.head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0

In [14]:
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
nba.index

RangeIndex(start=0, stop=458, step=1)

In [16]:
nba.values

array([['Avery Bradley', 'Boston Celtics', 0.0, ..., 180.0, 'Texas',
        7730337.0],
       ['Jae Crowder', 'Boston Celtics', 99.0, ..., 235.0, 'Marquette',
        6796117.0],
       ['John Holland', 'Boston Celtics', 30.0, ..., 205.0,
        'Boston University', nan],
       ...,
       ['Tibor Pleiss', 'Utah Jazz', 21.0, ..., 256.0, nan, 2900000.0],
       ['Jeff Withey', 'Utah Jazz', 24.0, ..., 231.0, 'Kansas', 947276.0],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)

In [24]:
#series
a=pd.Series(np.random.randint(10,30,40))
a.values

array([21, 16, 26, 26, 24, 28, 22, 25, 20, 15, 26, 14, 24, 19, 20, 13, 12,
       20, 15, 22, 10, 15, 29, 25, 15, 13, 21, 22, 27, 10, 12, 15, 24, 18,
       23, 19, 21, 13, 28, 24])

In [25]:
nba.shape

(458, 9)

In [26]:
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [27]:
nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [30]:
nba.axes

[RangeIndex(start=0, stop=458, step=1),
 Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
        'College', 'Salary'],
       dtype='object')]

In [35]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null object
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     373 non-null object
Salary      446 non-null float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [37]:
nba.get_dtype_counts()

float64    4
object     5
dtype: int64

# difference btw shared method

In [47]:
rev=pd.read_csv("revenue.csv",index_col = "Date")
rev.head(3)

        New York  Los Angeles  Miami
Date
1/1/16       985          122    499
1/2/16       738          788    534
1/3/16        14           20    933

In [48]:
S = pd.Series([1,2,3])
S

0    1
1    2
2    3
dtype: int64

In [49]:
rev.sum()

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [50]:
rev.sum(axis = 0) #column wise

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [53]:
rev.sum(axis = "index")  #column wise

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [56]:
rev.sum(axis = 1)  #row wise (axis = 'columns') works

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

# selecting one column from dataframe

In [72]:
nba = pd.read_csv("nba.csv")
nba.head(6)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0

In [73]:
nba.Name.head(6)

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
Name: Name, dtype: object

In [74]:
nba.Name
nba.Salary

Output = None

In [77]:
nba['Name']
nba['Salary']

0       7730337.0
1       6796117.0
2             NaN
3       1148640.0
4       5000000.0
5      12000000.0
6       1170960.0
7       2165160.0
8       1824360.0
9       3431040.0
10      2569260.0
11      6912869.0
12      3425510.0
13      1749840.0
14      2616975.0
15      3425510.0
16       845059.0
17      1500000.0
18      1335480.0
19      6300000.0
20      1599840.0
21       134215.0
22      1500000.0
23     19689000.0
24      1140240.0
25       947276.0
26       981348.0
27       947276.0
28       947276.0
29     11235955.0
          ...
428     8042895.0
429      625093.0
430      947276.0
431     6980802.0
432     2894059.0
433     6000000.0
434     5016000.0
435     3075880.0
436     4236287.0
437     2525160.0
438      525093.0
439     1415520.0
440     2854940.0
441     2637720.0
442     4775000.0
443     2658240.0
444     9463484.0
445     3777720.0
446    12000000.0
447     1175880.0
448    15409570.0
449     1348440.0
450     2050000.0
451      981348.0
452     2239800.0
453     2433333.0
454      900000.0
455     2900000.0
456      947276.0
457           NaN
Name: Salary, Length: 458, dtype: float64

In [78]:
type(nba['Name'])

pandas.core.series.Series

In [79]:
nba['Name'].head()

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: object

# select two or more columns from the dataframe

In [104]:
nba = pd.read_csv('nba.csv')
nba.head(7)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0

In [86]:
nba[['Name','Age']].head(4)

            Name   Age
0  Avery Bradley  25.0
1    Jae Crowder  25.0
2   John Holland  27.0
3    R.J. Hunter  22.0

In [87]:
type(nba[['Name','Age']].head(4))

pandas.core.frame.DataFrame

In [89]:
select = ['Name','Age','Salary']
nba[select].head(6)

            Name   Age      Salary
0  Avery Bradley  25.0   7730337.0
1    Jae Crowder  25.0   6796117.0
2   John Holland  27.0         NaN
3    R.J. Hunter  22.0   1148640.0
4  Jonas Jerebko  29.0   5000000.0
5   Amir Johnson  29.0  12000000.0

In [91]:
select = ['Name','Age','Salary']
for i in select:
    print(nba[i])

0                Avery Bradley
1                  Jae Crowder
2                 John Holland
3                  R.J. Hunter
4                Jonas Jerebko
5                 Amir Johnson
6                Jordan Mickey
7                 Kelly Olynyk
8                 Terry Rozier
9                 Marcus Smart
10             Jared Sullinger
11               Isaiah Thomas
12                 Evan Turner
13                 James Young
14                Tyler Zeller
15            Bojan Bogdanovic
16                Markel Brown
17             Wayne Ellington
18     Rondae Hollis-Jefferson
19                Jarrett Jack
20              Sergey Karasev
21             Sean Kilpatrick
22                Shane Larkin
23                 Brook Lopez
24            Chris McCullough
25                 Willie Reed
26             Thomas Robinson
27                  Henry Sims
28                Donald Sloan
29              Thaddeus Young
                ...
428            Al-Farouq Aminu
429            Pat Connaughton
430               Allen Crabbe
431                   Ed Davis
432           Maurice Harkless
433           Gerald Henderson
434                Chris Kaman
435             Meyers Leonard
436             Damian Lillard
437              C.J. McCollum
438               Luis Montero
439              Mason Plumlee
440              Brian Roberts
441                Noah Vonleh
442              Trevor Booker
443                 Trey Burke
444                 Alec Burks
445                 Dante Exum
446             Derrick Favors
447                Rudy Gobert
448             Gordon Hayward
449                Rodney Hood
450                 Joe Ingles
451              Chris Johnson
452                 Trey Lyles
453               Shelvin Mack
454                  Raul Neto
455               Tibor Pleiss
456                Jeff Withey
457                        NaN
Name: Name, Length: 458, dtype: object
0      25.0
1      25.0
2      27.0
3      22.0
4      29.0
5      29.0
6      21.0
7      25.0
8      22.0
9      22.0
10     24.0
11     27.0
12     27.0
13     20.0
14     26.0
15     27.0
16     24.0
17     28.0
18     21.0
19     32.0
20     22.0
21     26.0
22     23.0
23     28.0
24     21.0
25     26.0
26     25.0
27     26.0
28     28.0
29     27.0
       ...
428    25.0
429    23.0
430    24.0
431    27.0
432    23.0
433    28.0
434    34.0
435    24.0
436    25.0
437    24.0
438    23.0
439    26.0
440    30.0
441    20.0
442    28.0
443    23.0
444    24.0
445    20.0
446    24.0
447    23.0
448    26.0
449    23.0
450    28.0
451    26.0
452    20.0
453    26.0
454    24.0
455    26.0
456    26.0
457     NaN
Name: Age, Length: 458, dtype: float64
0       7730337.0
1       6796117.0
2             NaN
3       1148640.0
4       5000000.0
5      12000000.0
6       1170960.0
7       2165160.0
8       1824360.0
9       3431040.0
10      2569260.0
11      6912869.0
12      3425510.0
13      1749840.0
14      2616975.0
15      3425510.0
16       845059.0
17      1500000.0
18      1335480.0
19      6300000.0
20      1599840.0
21       134215.0
22      1500000.0
23     19689000.0
24      1140240.0
25       947276.0
26       981348.0
27       947276.0
28       947276.0
29     11235955.0
          ...
428     8042895.0
429      625093.0
430      947276.0
431     6980802.0
432     2894059.0
433     6000000.0
434     5016000.0
435     3075880.0
436     4236287.0
437     2525160.0
438      525093.0
439     1415520.0
440     2854940.0
441     2637720.0
442     4775000.0
443     2658240.0
444     9463484.0
445     3777720.0
446    12000000.0
447     1175880.0
448    15409570.0
449     1348440.0
450     2050000.0
451      981348.0
452     2239800.0
453     2433333.0
454      900000.0
455     2900000.0
456      947276.0
457           NaN
Name: Salary, Length: 458, dtype: float64

In [93]:
nba['sports'] = 'chandan'

In [94]:
nba.head(7)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,sports
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,chandan
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,chandan
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,chandan
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,chandan
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,chandan
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0,chandan
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0,chandan

In [105]:
nba.insert(4,column='some_numberr',value=np.random.randn(458))
nba

,Name,Team,Number,Position,some_numberr,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,0.524185,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,0.594773,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,-0.870696,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,-1.117677,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,0.263235,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,1.598363,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,-0.815103,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,-0.238781,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,-0.069008,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,-1.055542,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,-0.759063,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,-1.302286,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,-0.056142,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,1.870791,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,-0.528325,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,-0.060925,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,1.705050,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,-1.715985,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,-0.499087,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,0.540268,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,1.748733,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,-0.742748,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,0.932213,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,0.032023,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,-0.596830,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,-0.612713,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,1.630083,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,-0.097936,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,0.001822,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,-1.183711,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,0.020676,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,-0.139279,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,0.001817,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,2.265922,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,-0.039353,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,0.851462,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,-0.217289,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,-0.168885,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,0.575808,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,1.142604,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,0.870003,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,0.925965,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,1.150509,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,1.209058,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,0.700067,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,-0.400854,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,0.729338,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,0.336248,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,0.188828,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,0.622468,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,-0.304161,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,-0.386714,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,-0.925629,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,0.129031,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,-1.037696,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,-0.953912,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,-0.523572,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,2.594002,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,0.388924,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,-0.230045,NaN,NaN,NaN,NaN,NaN

# Broadcasting operation

In [46]:
nba = pd.read_csv('nba.csv')
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [8]:
nba['Age'].add(5)
nba['Age'] + 5

0      30.0
1      30.0
2      32.0
3      27.0
4      34.0
5      34.0
6      26.0
7      30.0
8      27.0
9      27.0
10     29.0
11     32.0
12     32.0
13     25.0
14     31.0
15     32.0
16     29.0
17     33.0
18     26.0
19     37.0
20     27.0
21     31.0
22     28.0
23     33.0
24     26.0
25     31.0
26     30.0
27     31.0
28     33.0
29     32.0
       ...
428    30.0
429    28.0
430    29.0
431    32.0
432    28.0
433    33.0
434    39.0
435    29.0
436    30.0
437    29.0
438    28.0
439    31.0
440    35.0
441    25.0
442    33.0
443    28.0
444    29.0
445    25.0
446    29.0
447    28.0
448    31.0
449    28.0
450    33.0
451    31.0
452    25.0
453    31.0
454    29.0
455    31.0
456    31.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [14]:
nba["Salary"].sub(100000)
nba['Salary'] - 100000

0       7630337.0
1       6696117.0
2             NaN
3       1048640.0
4       4900000.0
5      11900000.0
6       1070960.0
7       2065160.0
8       1724360.0
9       3331040.0
10      2469260.0
11      6812869.0
12      3325510.0
13      1649840.0
14      2516975.0
15      3325510.0
16       745059.0
17      1400000.0
18      1235480.0
19      6200000.0
20      1499840.0
21        34215.0
22      1400000.0
23     19589000.0
24      1040240.0
25       847276.0
26       881348.0
27       847276.0
28       847276.0
29     11135955.0
          ...
428     7942895.0
429      525093.0
430      847276.0
431     6880802.0
432     2794059.0
433     5900000.0
434     4916000.0
435     2975880.0
436     4136287.0
437     2425160.0
438      425093.0
439     1315520.0
440     2754940.0
441     2537720.0
442     4675000.0
443     2558240.0
444     9363484.0
445     3677720.0
446    11900000.0
447     1075880.0
448    15309570.0
449     1248440.0
450     1950000.0
451      881348.0
452     2139800.0
453     2333333.0
454      800000.0
455     2800000.0
456      847276.0
457           NaN
Name: Salary, Length: 458, dtype: float64

In [16]:
nba['Weight'].mul(4.3657) 
nba["Weight"] * 4.3657

0       785.8260
1      1025.9395
2       894.9685
3       807.6545
4      1008.4767
5      1047.7680
6      1025.9395
7      1039.0366
8       829.4830
9       960.4540
10     1135.0820
11      807.6545
12      960.4540
13      938.6255
14     1104.5221
15      942.9912
16      829.4830
17      873.1400
18      960.4540
19      873.1400
20      908.0656
21      956.0883
22      763.9975
23     1200.5675
24      873.1400
25      960.4540
26     1034.6709
27     1082.6936
28      894.9685
29      964.8197
         ...
428     938.6255
429     899.3342
430     916.7970
431    1047.7680
432     938.6255
433     938.6255
434    1156.9105
435    1069.5965
436     851.3115
437     873.1400
438     807.6545
439    1025.9395
440     755.2661
441    1047.7680
442     995.3796
443     833.8487
444     934.2598
445     829.4830
446    1156.9105
447    1069.5965
448     986.6482
449     899.3342
450     986.6482
451     899.3342
452    1021.5738
453     886.2371
454     781.4603
455    1117.6192
456    1008.4767
457          NaN
Name: Weight, Length: 458, dtype: float64

In [18]:
nba['weight to Kg'] = nba['Weight'].mul(4.56)
nba.head(6)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,weight to Kg
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,820.80
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,1071.60
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,934.80
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,843.60
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,1053.36
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0,1094.40

In [24]:
nba['calcu'] = "NaN"
nba.head(2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,weight to Kg,calcu
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,820.8,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,1071.6,NaN

In [26]:
nba['calcu'] = nba['Salary'] - nba['weight to Kg']
nba.head(2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,weight to Kg,calcu
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,820.8,7729516.2
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,1071.6,6795045.4

In [47]:
nba.insert(2,column = "Full Name",value=(nba['Name']+'   '+nba['Team']))
nba.head(3)

,Name,Team,Full Name,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,Avery Bradley Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,Jae Crowder Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,John Holland Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

# .value_count() method

In [49]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [58]:
nba['Team'].value_counts()
nba["Weight"].value_counts().head(2)
nba["Position"].value_counts().tail()
nba["Salary"].value_counts()

947276.0      31
845059.0      18
525093.0      13
981348.0       6
1100602.0      5
16407500.0     5
5000000.0      5
12000000.0     5
8000000.0      5
4000000.0      5
3000000.0      4
7000000.0      4
2814000.0      4
1000000.0      4
19689000.0     4
200600.0       3
8500000.0      3
2500000.0      3
1015421.0      3
2854940.0      3
13500000.0     3
5543725.0      3
2288205.0      2
1270964.0      2
2900000.0      2
1007026.0      2
111444.0       2
13000000.0     2
1500000.0      2
1842000.0      2
              ..
2239800.0      1
1474440.0      1
19688000.0     1
7900000.0      1
2008748.0      1
13800000.0     1
2841960.0      1
1404600.0      1
1584480.0      1
273038.0       1
9213483.0      1
3272091.0      1
3075880.0      1
2250000.0      1
4626960.0      1
1304520.0      1
12100000.0     1
7500000.0      1
295327.0       1
2836186.0      1
6486486.0      1
5016000.0      1
3333333.0      1
1824360.0      1
8042895.0      1
1242720.0      1
2489530.0      1
5103120.0      1
9463484.0      1
700902.0       1
Name: Salary, Length: 309, dtype: int64

# drop columns

In [6]:
nba = pd.read_csv("nba.csv")
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [6]:
nba.tail(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
nba.dropna()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
35,Cleanthony Early,New York Knicks,11.0,SF,25.0,6-8,210.0,Wichita State,845059.0
36,Langston Galloway,New York Knicks,2.0,SG,24.0,6-2,200.0,Saint Joseph's,845059.0
...,...,...,...,...,...,...,...,...,...
422,Cameron Payne,Oklahoma City Thunder,22.0,PG,21.0,6-3,185.0,Murray State,2021520.0
423,Andre Roberson,Oklahoma City Thunder,21.0,SG,24.0,6-7,210.0,Colorado,1210800.0
424,Kyle Singler,Oklahoma City Thunder,5.0,SF,28.0,6-8,228.0,Duke,4500000.0
425,Dion Waiters,Oklahoma City Thunder,3.0,SG,24.0,6-4,220.0,Syracuse,5138430.0
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218.0
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [13]:
nba.dropna(how="all",inplace=True)
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [14]:
nba.dropna(axis = 1)

,Name,Team,Number,Position,Age,Height,Weight
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0
...,...,...,...,...,...,...,...
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0

In [15]:
nba.dropna(subset=["Salary"])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
...,...,...,...,...,...,...,...,...,...
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [20]:
a = nba.isnull()
a.head()

    Name   Team  Number  Position    Age  Height  Weight  College  Salary
0  False  False   False     False  False   False   False    False   False
1  False  False   False     False  False   False   False    False   False
2  False  False   False     False  False   False   False    False    True
3  False  False   False     False  False   False   False    False   False
4  False  False   False     False  False   False   False     True   False

In [23]:
a =nba.isna()
a.tail()

      Name   Team  Number  Position    Age  Height  Weight  College  Salary
452  False  False   False     False  False   False   False    False   False
453  False  False   False     False  False   False   False    False   False
454  False  False   False     False  False   False   False     True   False
455  False  False   False     False  False   False   False     True   False
456  False  False   False     False  False   False   False    False   False

In [41]:
nba["alla"].isnull().mean()>0.5

False

In [40]:
nba["alla"] = ""
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,alla
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,..
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,..
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,..
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,..
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,..
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0,..
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0,..
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0,..
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0,..
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0,..
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0,..
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0,..
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0,..
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0,..
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0,..
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0,..
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0,..
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0,..
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0,..
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0,..
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0,..
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0,..
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0,..
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0,..
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0,..
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0,..
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0,..
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0,..
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0,..
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0,..
...,...,...,...,...,...,...,...,...,...,...
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0,..
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0,..
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0,..
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0,..
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0,..
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0,..
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0,..
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0,..
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0,..
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0,..
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0,..
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0,..
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0,..
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0,..
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0,..
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0,..
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0,..
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0,..
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0,..
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0,..
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0,..
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0,..
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0,..
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0,..
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0,..
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0,..
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,..
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,..
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,..
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,..

In [4]:
nba.drop_duplicates(subset="Age")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0
34,Jose Calderon,New York Knicks,3.0,PG,34.0,6-3,200.0,NaN,7402812.0
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,NaN
72,Luis Scola,Toronto Raptors,4.0,PF,36.0,6-9,240.0,NaN,2900000.0
78,Andrew Bogut,Golden State Warriors,12.0,C,31.0,7-0,260.0,Utah,13800000.0
101,Paul Pierce,Los Angeles Clippers,34.0,SF,38.0,6-7,235.0,Kansas,3376000.0
102,Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,NaN,947726.0
122,Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,2127840.0
154,Mike Dunleavy,Chicago Bulls,34.0,SG,35.0,6-9,230.0,Duke,4500000.0
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# .fillna()

In [7]:
nba.fillna(value = "something")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,Texas,7.73034e+06
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6.79612e+06
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,something
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1.14864e+06
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,something,5e+06
5,Amir Johnson,Boston Celtics,90,PF,29,6-9,240,something,1.2e+07
6,Jordan Mickey,Boston Celtics,55,PF,21,6-8,235,LSU,1.17096e+06
7,Kelly Olynyk,Boston Celtics,41,C,25,7-0,238,Gonzaga,2.16516e+06
8,Terry Rozier,Boston Celtics,12,PG,22,6-2,190,Louisville,1.82436e+06
9,Marcus Smart,Boston Celtics,36,PG,22,6-4,220,Oklahoma State,3.43104e+06
10,Jared Sullinger,Boston Celtics,7,C,24,6-9,260,Ohio State,2.56926e+06
11,Isaiah Thomas,Boston Celtics,4,PG,27,5-9,185,Washington,6.91287e+06
12,Evan Turner,Boston Celtics,11,SG,27,6-7,220,Ohio State,3.42551e+06
13,James Young,Boston Celtics,13,SG,20,6-6,215,Kentucky,1.74984e+06
14,Tyler Zeller,Boston Celtics,44,C,26,7-0,253,North Carolina,2.61698e+06
15,Bojan Bogdanovic,Brooklyn Nets,44,SG,27,6-8,216,something,3.42551e+06
16,Markel Brown,Brooklyn Nets,22,SG,24,6-3,190,Oklahoma State,845059
17,Wayne Ellington,Brooklyn Nets,21,SG,28,6-4,200,North Carolina,1.5e+06
18,Rondae Hollis-Jefferson,Brooklyn Nets,24,SG,21,6-7,220,Arizona,1.33548e+06
19,Jarrett Jack,Brooklyn Nets,2,PG,32,6-3,200,Georgia Tech,6.3e+06
20,Sergey Karasev,Brooklyn Nets,10,SG,22,6-7,208,something,1.59984e+06
21,Sean Kilpatrick,Brooklyn Nets,6,SG,26,6-4,219,Cincinnati,134215
22,Shane Larkin,Brooklyn Nets,0,PG,23,5-11,175,Miami (FL),1.5e+06
23,Brook Lopez,Brooklyn Nets,11,C,28,7-0,275,Stanford,1.9689e+07
24,Chris McCullough,Brooklyn Nets,1,PF,21,6-11,200,Syracuse,1.14024e+06
25,Willie Reed,Brooklyn Nets,33,PF,26,6-10,220,Saint Louis,947276
26,Thomas Robinson,Brooklyn Nets,41,PF,25,6-10,237,Kansas,981348
27,Henry Sims,Brooklyn Nets,14,C,26,6-10,248,Georgetown,947276
28,Donald Sloan,Brooklyn Nets,15,PG,28,6-3,205,Texas A&M,947276
29,Thaddeus Young,Brooklyn Nets,30,PF,27,6-8,221,Georgia Tech,1.1236e+07
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8,SF,25,6-9,215,Wake Forest,8.0429e+06
429,Pat Connaughton,Portland Trail Blazers,5,SG,23,6-5,206,Notre Dame,625093
430,Allen Crabbe,Portland Trail Blazers,23,SG,24,6-6,210,California,947276
431,Ed Davis,Portland Trail Blazers,17,C,27,6-10,240,North Carolina,6.9808e+06
432,Maurice Harkless,Portland Trail Blazers,4,SF,23,6-9,215,St. John's,2.89406e+06
433,Gerald Henderson,Portland Trail Blazers,9,SG,28,6-5,215,Duke,6e+06
434,Chris Kaman,Portland Trail Blazers,35,C,34,7-0,265,Central Michigan,5.016e+06
435,Meyers Leonard,Portland Trail Blazers,11,PF,24,7-1,245,Illinois,3.07588e+06
436,Damian Lillard,Portland Trail Blazers,0,PG,25,6-3,195,Weber State,4.23629e+06
437,C.J. McCollum,Portland Trail Blazers,3,SG,24,6-4,200,Lehigh,2.52516e+06
438,Luis Montero,Portland Trail Blazers,44,SG,23,6-7,185,Westchester CC,525093
439,Mason Plumlee,Portland Trail Blazers,24,C,26,6-11,235,Duke,1.41552e+06
440,Brian Roberts,Portland Trail Blazers,2,PG,30,6-1,173,Dayton,2.85494e+06
441,Noah Vonleh,Portland Trail Blazers,21,PF,20,6-9,240,Indiana,2.63772e+06
442,Trevor Booker,Utah Jazz,33,PF,28,6-8,228,Clemson,4.775e+06
443,Trey Burke,Utah Jazz,3,PG,23,6-1,191,Michigan,2.65824e+06
444,Alec Burks,Utah Jazz,10,SG,24,6-6,214,Colorado,9.46348e+06
445,Dante Exum,Utah Jazz,11,PG,20,6-6,190,something,3.77772e+06
446,Derrick Favors,Utah Jazz,15,PF,24,6-10,265,Georgia Tech,1.2e+07
447,Rudy Gobert,Utah Jazz,27,C,23,7-1,245,something,1.17588e+06
448,Gordon Hayward,Utah Jazz,20,SF,26,6-8,226,Butler,1.54096e+07
449,Rodney Hood,Utah Jazz,5,SG,23,6-8,206,Duke,1.34844e+06
450,Joe Ingles,Utah Jazz,2,SF,28,6-8,226,something,2.05e+06
451,Chris Johnson,Utah Jazz,23,SF,26,6-6,206,Dayton,981348
452,Trey Lyles,Utah Jazz,41,PF,20,6-10,234,Kentucky,2.2398e+06
453,Shelvin Mack,Utah Jazz,8,PG,26,6-3,203,Butler,2.43333e+06
454,Raul Neto,Utah Jazz,25,PG,24,6-1,179,something,900000
455,Tibor Pleiss,Utah Jazz,21,C,26,7-3,256,something,2.9e+06
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276
457,something,something,something,something,something,something,something,something,something

In [8]:
nba.fillna(value = "hello",axis=0, limit=)

ValueError: Limit must be an integer